title: Tiffany L. Coelho
url: "https://tiffanylakecoelho.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/tiffanylakecoelho"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume"
 - name: "Contact"
   link: "contact"
   name: "Books"
   link: "books"
